services:
  - type: web
    name: gfx-giveaway-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: TOKEN
        sync: false
      - key: WINNER_LOG_CHANNEL_ID
        value: 1535915013729026150
      - key: SERVER_TAG
        value: GFX
      - key: SERVER_TAG_ROLE_ID
        value: 1535157101310115921
      - key: GIVEAWAY_WINNER_ROLE_ID
        value: 1532972012341956678
      - key: GUILD_ID
        value: 1395645163547791370
      - key: DASHBOARD_PASSWORD
        sync: false
      - key: AUTH_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        value: 365172990460-drv1dv87haj14c7tftam010ikrgt81i5.apps.googleusercontent.com
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        value: https://gfx-giveaway-bot.onrender.com/api/auth/google/callback
      - key: ADMIN_EMAILS
        value: mauryaaryan29@gmail.com
      - key: NODE_ENV
        value: production
      - key: AUTO_OPEN_BROWSER
        value: "false"
